#!/usr/bin/env python3
"""Build a QuestID -> patch table from Wago plus supplementary sources.

Wago remains authoritative wherever its retail history can distinguish the
quest's first appearance.  For Wago's ``at_or_before`` baseline (7.3.5) and
IDs absent from Wago, the precedence is ATT (direct quest timeline before
inherited group timeline), then Warcraft Wiki.  Conflicts are reported, while
the higher-priority source is selected.

The default output is under .cache so an audit cannot accidentally replace the
released addon data.  Use --out-dir data only after reviewing the report.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def patch_code(patch: str) -> int:
    a, b, c = (int(part) for part in patch.split("."))
    return a * 10000 + b * 100 + c


def patch_key(patch: str) -> tuple[int, int, int]:
    return tuple(int(part) for part in patch.split("."))


def read_rows(path: Path) -> dict[int, dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return {int(row["quest_id"]): row for row in csv.DictReader(handle)}


def choose(
    qid: int,
    wago: dict[int, dict[str, str]],
    att: dict[int, dict[str, str]],
    wiki: dict[int, dict[str, str]],
    baseline: str,
    conflicts: dict[str, list[dict[str, str]]],
) -> tuple[str, str] | None:
    wago_row = wago.get(qid)
    if wago_row and wago_row.get("source") != "at_or_before":
        return wago_row["patch"], "wago"

    candidates: list[tuple[str, str, str]] = []
    if qid in att and att[qid].get("source") == "direct":
        candidates.append((att[qid]["patch"], "att_direct", "direct"))
    if qid in att and att[qid].get("source", "").startswith("direct_conflict"):
        candidates.append((att[qid]["patch"], "att_direct_conflict_latest", "direct"))
    if qid in att and att[qid].get("source") == "inherited":
        candidates.append((att[qid]["patch"], "att_inherited", "inherited"))
    if qid in att and att[qid].get("source", "").startswith("inherited_conflict"):
        candidates.append((att[qid]["patch"], "att_inherited_conflict_latest", "inherited"))
    if qid in wiki:
        candidates.append((wiki[qid]["patch"], "warcraft_wiki", "explicit"))
    if qid in att and att[qid].get("source") not in {
        "direct", "inherited", "direct_conflict_latest", "inherited_conflict_latest"
    }:
        source = att[qid].get("source", "att")
        candidates.append((att[qid]["patch"], f"att_{source}", source))

    patches = {patch for patch, _source, _kind in candidates}
    if len(patches) > 1:
        conflicts[str(qid)] = [
            {"patch": patch, "source": source}
            for patch, source, _kind in candidates
        ]
        # The candidate list is ordered by the deliberate source preference.
        return candidates[0][0], candidates[0][1]
    if candidates:
        patch, source, _kind = candidates[0]
        return patch, source
    if wago_row:
        return baseline, "wago_at_or_before"
    return None


def write_outputs(
    out_dir: Path,
    assignments: dict[int, tuple[str, str]],
    wago: dict[int, dict[str, str]],
    meta: dict,
    conflicts: dict[str, list[dict[str, str]]],
    universe_count: int,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for qid in sorted(assignments):
        patch, source = assignments[qid]
        old = wago.get(qid, {})
        rows.append(
            [
                qid,
                patch,
                patch_code(patch),
                old.get("id_first", patch),
                old.get("poi_first", ""),
                source,
            ]
        )

    with (out_dir / "quest_patches.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["quest_id", "patch", "patch_code", "id_first", "poi_first", "source"])
        writer.writerows(rows)

    newest = meta["newest_build"]
    lua = [
        "-- Generated by tools/build_quest_patches_hybrid.py. Do not edit.",
        "-- Wago is primary; ATT then Wiki supplement its baseline by preference.",
        f"-- Newest retail snapshot: {newest}",
        "AsItWasQuestPatchNewestBuild = " + json.dumps(newest),
        "AsItWasQuestPatch = {",
    ]
    lua.extend(f"[{qid}]={patch_code(patch)}," for qid, (patch, _source) in sorted(assignments.items()))
    lua.extend(["}", ""])
    (out_dir / "QuestPatches.lua").write_text("\n".join(lua), encoding="utf-8")

    all_patches = {patch for patch, _source in assignments.values()}
    builds = {item["patch"]: item["build"] for item in meta["snapshots"]}
    patch_lua = [
        "-- Generated by tools/build_quest_patches_hybrid.py. Do not edit.",
        "-- Wago snapshots plus patches found by supplementary sources.",
        "AsItWasPatches = {",
    ]
    for patch in sorted(all_patches, key=patch_key):
        patch_lua.append(
            f'    {{patch="{patch}", code={patch_code(patch)}, build="{builds.get(patch, "supplementary")}"}},'
        )
    patch_lua.extend(["}", ""])
    (out_dir / "PatchList.lua").write_text("\n".join(patch_lua), encoding="utf-8")

    counts: dict[str, int] = {}
    for _patch, source in assignments.values():
        counts[source] = counts.get(source, 0) + 1
    report = {
        **meta,
        "source": "wago_primary_att_wiki_supplement",
        "quest_count": len(assignments),
        "counts": counts,
        "conflict_count": len(conflicts),
        "conflict_examples": dict(list(sorted(conflicts.items()))[:100]),
        # This is intentionally scoped to the IDs supplied by the input CSVs;
        # it is not a claim that the union is a complete WoW quest universe.
        "candidate_universe_count": universe_count,
        "unresolved_candidate_ids": universe_count - len(assignments),
        "unresolved_missing": universe_count - len(assignments),
        "unresolved_missing_definition": (
            "IDs missing from the union of the supplied Wago, ATT, and Wiki CSVs"
        ),
    }
    (out_dir / "quest_patches_meta.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    (out_dir / "quest_patches_conflicts.json").write_text(
        json.dumps(conflicts, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(report, indent=2))


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wago", type=Path, default=root / "data" / "quest_patches.csv")
    parser.add_argument("--att", type=Path, required=True, help="CSV from analyze_att_quest_patches.py")
    parser.add_argument("--wiki", type=Path, help="CSV from build_quest_patches_wiki.py")
    parser.add_argument("--out-dir", type=Path, default=root / ".cache" / "quest-patches-hybrid")
    args = parser.parse_args()

    wago = read_rows(args.wago)
    att = read_rows(args.att)
    wiki = read_rows(args.wiki) if args.wiki else {}
    old_meta = json.loads((args.wago.parent / "quest_patches_meta.json").read_text(encoding="utf-8"))
    baseline = old_meta.get("baseline", "7.3.5")
    assignments: dict[int, tuple[str, str]] = {}
    conflicts: dict[str, list[dict[str, str]]] = {}
    for qid in sorted(set(wago) | set(att) | set(wiki)):
        selected = choose(qid, wago, att, wiki, baseline, conflicts)
        if selected:
            assignments[qid] = selected
    write_outputs(
        args.out_dir,
        assignments,
        wago,
        old_meta,
        conflicts,
        len(set(wago) | set(att) | set(wiki)),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
